---
# defaults file for django_web
python_img_version : "3.9.1-buster"
pip_version : "3"
django_port : "8000"
app_dir : "/var/www/django/api-rest-example"
app_repo : "https://github.com/fabry22/cablemodems-api.git"
django_web_ip : "172.1.1.200"