---
- name: Run Python container.
  docker_container:
    image: "python:{{ python_img_version }}"
    name: django-web
    state: started
    ports: "{{ django_port }}:{{ django_port }}"
    detach: yes
    interactive: yes
    networks:
      - name: "{{ docker_net }}"
        ipv4_address: "{{ django_web_ip }}"

- name: Add Python container to inventory.
  add_host:
    name: django-web
    ansible_connection: community.general.docker
  changed_when: false

- name: Install apt packages.
  delegate_to: django-web
  apt:
    name:
      - "python{{ pip_version }}-pip "
      - apt-utils
      - libmariadb-dev
      - gcc
      - git
    state: latest
    update_cache: yes

- name: Create django app dir.
  delegate_to: django-web
  file:
    path: "{{ app_dir }}"
    state: directory
    mode: '0644'

- name: Pull django app code.
  delegate_to: django-web
  git:
    repo: "{{ app_repo }}"
    dest: "{{ app_dir }}"
    update: yes

- name: Update requirements.
  delegate_to: django-web
  pip:
    requirements: "{{ app_dir }}/requirements.txt"

- name: Launch server.
  delegate_to: django-web
  raw:
    "cd {{ app_dir }} && python3 web/manage.py runserver 0.0.0.0:{{ django_port }}"
